
package ws_eurekabank_soap_java_clienteconsola;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSEureka", targetNamespace = "http://ws.monster.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEureka {


    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "resultadoLogin", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.LoginResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/loginRequest", output = "http://ws.monster.edu.ec/WSEureka/loginResponse")
    public boolean login(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param cuenta
     * @return
     *     returns java.util.List<ws_eurekabank_soap_java_clienteconsola.Movimiento>
     */
    @WebMethod
    @WebResult(name = "movimiento", targetNamespace = "")
    @RequestWrapper(localName = "traerMovimientos", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.TraerMovimientos")
    @ResponseWrapper(localName = "traerMovimientosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.TraerMovimientosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/traerMovimientosRequest", output = "http://ws.monster.edu.ec/WSEureka/traerMovimientosResponse")
    public List<Movimiento> traerMovimientos(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

    /**
     * 
     * @param importe
     * @param cuentaOrigen
     * @param cuentaDestino
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "estado", targetNamespace = "")
    @RequestWrapper(localName = "regTransferencia", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegTransferencia")
    @ResponseWrapper(localName = "regTransferenciaResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegTransferenciaResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regTransferenciaRequest", output = "http://ws.monster.edu.ec/WSEureka/regTransferenciaResponse")
    public int regTransferencia(
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @param importe
     * @param cuenta
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "estado", targetNamespace = "")
    @RequestWrapper(localName = "regRetiro", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegRetiro")
    @ResponseWrapper(localName = "regRetiroResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegRetiroResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regRetiroRequest", output = "http://ws.monster.edu.ec/WSEureka/regRetiroResponse")
    public int regRetiro(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @param importe
     * @param cuenta
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "estado", targetNamespace = "")
    @RequestWrapper(localName = "regDeposito", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegDeposito")
    @ResponseWrapper(localName = "regDepositoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ws_eurekabank_soap_java_clienteconsola.RegDepositoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regDepositoRequest", output = "http://ws.monster.edu.ec/WSEureka/regDepositoResponse")
    public int regDeposito(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

}
